name: Auto Label PR

on:
  workflow_call:
    inputs:
      author-login:
        required: true
        type: string
      pr-number:
        required: true
        type: number

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            const authorLogin = "${{ inputs.author-login }}";

            if (authorLogin === 'citygeo-bot[bot]' || authorLogin.includes('citygeo-bot')) {
              console.log(`Skipping: PR was created by the Renovate bot (${authorLogin}).`);
              return;
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number("${{ inputs.pr-number }}"),
              labels: ['needs-review']
            });
