name: Auto Label PR

on:
  workflow_call:
    inputs:
      author-login:
        required: true
        type: string
      pr-number:
        required: true
        type: number

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-gh-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.CITYGEO_BOT_GH_APP_ID }}
          private-key: ${{ secrets.CITYGEO_BOT_GH_APP_PRIVATE_KEY }}
          owner: CityOfPhiladelphia
          repositories: |
            ${{ github.repository }}
      - name: Add label
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ steps.generate-gh-app-token.outputs.token }}
          script: |
            const authorLogin = "${{ inputs.author-login }}";

            if (authorLogin === 'citygeo-bot[bot]' || authorLogin.includes('citygeo-bot')) {
              console.log(`Skipping: PR was created by the Renovate bot (${authorLogin}).`);
              return;
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number("${{ inputs.pr-number }}"),
              labels: ['needs-review']
            });
