name: Terraform Plan

on:
  workflow_call:
    inputs:
      tf_token_keeper_path:
        required: true
        type: string
      aws_access_key_id_keeper_path:
        required: true
        type: string
      aws_secret_access_key_keeper_path:
        required: true
        type: string
      terraform_keeper_key_keeper_path:
        type: string
        default: dSbGhN1_J1tqv-4dzrm8hw/field/password
      tf_dir:
        required: true
        type: string
        default: "."
      cli_opts:
        required: false
        type: string
        default: " "
    secrets:
      KSM_CONFIG:
        required: true

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        name: Checkout source code
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@310b9e6bd9d95e6fd49881e72c35a0a23cf5a0f0 # master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            ${{ inputs.tf_token_keeper_path }} > env:TF_TOKEN
            ${{ inputs.aws_access_key_id_keeper_path }} > env:AWS_ACCESS_KEY_ID
            ${{ inputs.aws_secret_access_key_keeper_path }} > env:AWS_SECRET_ACCESS_KEY
            ${{ inputs.terraform_keeper_key_keeper_path }} > env:TF_KEEPER_KEY
      - name: Setup Nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          check-latest: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          cli_config_credentials_token: ${{ env.TF_TOKEN }}
      - name: Terraform Init
        run: |
          cd ${{ inputs.tf_dir }}
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ inputs.tf_dir }}
          terraform plan -no-color -lock-timeout=300s
        env:
          KEEPER_CREDENTIAL: ${{ env.TF_KEEPER_KEY }}
      - name: Write terraform plan output to pull request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
          TF_DIR: "${{ inputs.tf_dir }}"
          PLAN_OUTCOME: "${{ steps.plan.outcome }}"
          GITHUB_ACTOR: "${{ github.actor }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(`Terraform plan output for \`${process.env.TF_DIR}\``);
            });

            const hasChanges = process.env.PLAN.indexOf("No changes. Your infrastructure matches the configuration.") >= 0 ? 'no' : 'yes'

            let processedPlan = process.env.PLAN;

            const tfModifyIndex = process.env.PLAN.indexOf("Terraform will perform the following actions:")
            if (tfModifyIndex >= 0) {
              processedPlan = process.env.PLAN.slice(tfModifyIndex) 
            }

            const output = `### Terraform plan output for \`${process.env.TF_DIR}\`
            #### Contains changes: \`${hasChanges}\`

            <details><summary>Show Plan</summary>

            \`\`\`
            ${processedPlan}
            \`\`\`

            </details>

            *Pusher: @${process.env.GITHUB_ACTOR}*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output,
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output,
              });
            }
