name: Terraform Format

on:
  workflow_call:
    inputs:
      parent_tf_dir:
        required: true
        type: string
        description: Parent directory where all Terraform files are underneath
        default: "."
      cli_opts:
        required: false
        type: string
        default: " "

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          check-latest: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          cli_config_credentials_token: AAA
      - name: Terraform Format
        run: |
          cd $TF_DIR
          terraform fmt -recursive -check ${{ inputs.cli_opts }} .
