name: Tofu Apply

on:
  workflow_call:
    inputs:
      deploy_environment:
        type: string
        default: ""
      tf_dir:
        required: true
        type: string
        default: "."
      cli_opts:
        required: false
        type: string
        default: " "
    secrets:
      CITYGEO_AWS_ACCESS_KEY_ID:
        required: true
      CITYGEO_AWS_SECRET_ACCESS_KEY:
        required: true
      TF_KEEPER_KEY:
        required: true

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy_environment }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        name: Checkout source code
      - name: Setup Terraform
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2
      - name: Tofu Init
        run: |
          cd ${{ inputs.tf_dir }}
          tofu init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CITYGEO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CITYGEO_AWS_SECRET_ACCESS_KEY }}
      - name: Tofu Apply
        run: |
          cd ${{ inputs.tf_dir }}
          tofu apply -auto-approve -lock-timeout=120s -input=false ${{ inputs.cli_opts }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CITYGEO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CITYGEO_AWS_SECRET_ACCESS_KEY }}
          KEEPER_CREDENTIAL: ${{ secrets.TF_KEEPER_KEY }}
